// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Footer from "./components/Footer";
// import Navbar from "./components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <div className="flex flex-col min-h-screen">

//           {/*  Navbar */}
//           <Navbar />

//           <main className="flex-grow container mx-auto px-4 md:px-6 lg:px-8">
//             {children}
//           </main> 
          
//           {/* Footer */}
//           <Footer />
//         </div>
        
//       </body>
      
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
// import { ThemeProvider } from "./context/ThemeProvider"; // Import ThemeProvider
import { ThemeProvider } from "@/context/ThemeProvider"; // Import ThemeProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <html lang="en">
    <html lang="en" data-theme="light">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider> {/* 🔹 Wrap app inside ThemeProvider */}
          <div className="flex flex-col min-h-screen">

            {/*  Navbar */}
            <Navbar />

            <main className="flex-grow container mx-auto px-4 md:px-6 lg:px-8">
              {children}
            </main> 
            
            {/* Footer */}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
